version: "3.9"
services:
  backend:
    restart: always
    build: server/backend
    ports:
      - "5000:5000"
    env_file:
      - postgres-variables.env
    depends_on:
      - db
  frontend:
    restart: always
    build: server/frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - postgres-variables.env
  worker:
    restart: always
    build: worker
    volumes:
      - ./worker/credentials:/credentials
    env_file:
      - postgres-variables.env
      - spreadsheet-variables.env
      - telegram-variables.env
    depends_on:
      - db
      - backend